---
name: test
on:
  pull_request:
  push:
    branches:
    - gh-readonly-queue/**
    - master
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v2
    - uses: actions/cache@v3
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel-cache
    - name: Run tests
      run: |
        bazel run //:buildifier
        bazel test //...
